rds-stress: Fix usage() message compiler warning
Orabug: 34484319

The fix introduced by 3baa4956 ("rds-stress: Add long option syntax to
usage output") introduced a build warning:

rds-stress.c: In function 'usage':
rds-stress.c:465:2: warning: too many arguments for format

The usage print statement is missing format specifiers for one of its
options. Reviewing the original print specification, the arguments are
used to provide the default values for IPv4 and IPv6 ack message
lengths.

Fixes: 3baa4956ff53 ("rds-stress: Add long option syntax to usage output")
Signed-off-by: Mark Haywood <mark.haywood@oracle.com>
Reviewed-by: Gerd Rausch <gerd.rausch@oracle.com>
Reviewed-by: Sharath Srinivasan <sharath.srinivasan@oracle.com>